# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ea3adae2b190a928bfaf1be56503ac701719720b2a31d69c628c8a459659114a0aafa7506ce48c5f6c6b53d12bddbf377d713ee102bc16c961ad5109aeb8408

test:
  secret_key_base: 12b9e27f6df9a922ef7a1aa601bc7c9c16db27656ca237d6a7dc430a212953d5c17fd405a5b545fd1ea1b795249ae4708e6e22cd71b2f151fcdda93852d0bdf2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
